---
# file: project/ansible-nagios-role.yml

- hosts: ansible-nagios-role
  become: false
  gather_facts: true
  pre_tasks:

    - set_fact: fact_role_name="{{ lookup('env','ANSIBLE_ROLE_NAME') }}"
    - debug: var=fact_role_name

    - set_fact: fact_role_path="{{ lookup('pipe','pwd') }}/roles/ansible-nagios-role"
    - debug: var=fact_role_path

  roles:

    - ansible-nagios-role
